# Generated by Django 5.1.1 on 2024-09-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=255)),
                ("watermark", models.CharField(blank=True, max_length=255, null=True)),
                ("director_first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("director_last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("director_middle_name", models.CharField(blank=True, max_length=255, null=True)),
                ("director_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("director_phone", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
