# Generated by Django 5.1.1 on 2024-09-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0001_initial"),
        ("users", "0003_alter_user_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_agencies",
                to="users.user",
            ),
        ),
    ]
