# Generated by Django 5.1.1 on 2024-09-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0001_initial"),
        ("users", "0002_user_agency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="agency",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="users", to="agencies.agency"),
        ),
    ]
